@startuml Login

participant Usuario
participant Sistema
participant BaseDatos
participant ServidorCorreo

' registro de usuario 
Usuario -> Sistema: Solicita Registro
activate Sistema
Sistema -> BaseDatos: nombre de usuario 
activate BaseDatos
BaseDatos -> BaseDatos: Verifica nombre de usuario unico
BaseDatos -> Sistema: Resultado de verificacion
deactivate BaseDatos

Sistema -> BaseDatos: direccion de correo valido 
activate BaseDatos
BaseDatos -> BaseDatos: Verifica direccion de correo valido
BaseDatos -> Sistema: Resultado de verificacion
deactivate BaseDatos

Sistema -> Sistema: verifica contraseña segura  
Sistema -> Sistema: genera codigo de verificacion 
Sistema -> ServidorCorreo: Enviar correo de verificación
deactivate Sistema
activate ServidorCorreo
ServidorCorreo -> Usuario: Correo de verificación
deactivate ServidorCorreo
Usuario -> Sistema: Ingresa codigo de verificacion
activate Sistema
Sistema -> Sistema: verifica codigo 
Sistema -> BaseDatos: Almacena datos del nuevo usuario
activate BaseDatos
deactivate BaseDatos
deactivate Sistema
' Inicio de Sesión 
Usuario -> Sistema: Iniciar sesión
activate Sistema
Sistema -> Sistema: Verificar credenciales
Sistema -> Sistema: Autenticar usuario
Sistema --> Usuario: Acceso concedido
deactivate Sistema


' olvido de contraseña 
Usuario -> Sistema: Olvidé mi contraseña
activate Sistema
activate BaseDatos
BaseDatos -> BaseDatos: Verifica direccion de correo
BaseDatos -> Sistema: dirección de correo electrónico
deactivate BaseDatos
Sistema -> Sistema: Genera enlace para restablecer contraseña
Sistema -> ServidorCorreo: Envia correo 
deactivate Sistema
activate ServidorCorreo
ServidorCorreo --> Usuario: Correo con enlace
deactivate ServidorCorreo
Usuario -> Sistema: Ingresa nueva contraseña
activate Sistema
activate BaseDatos
BaseDatos -> BaseDatos: Verifica nueva contraseña
BaseDatos -> Sistema: nueva contraseña
Sistema -> BaseDatos: Actualiza contraseña del usuario
deactivate BaseDatos
Sistema -> Usuario: Confirma restablecimiento de contraseña
deactivate Sistema

' cerrar sesion 
Usuario -> Sistema: Cerrar sesión
activate Sistema
Sistema -> Sistema: Cerrar sesión del usuario
Sistema --> Usuario: Sesión cerrada
deactivate Sistema
@enduml