@startuml mecanica
participant Jugador
participant Sistema
participant Sala
participant Mecanica 
participant Recompensas

Jugador -> Sistema: Ingresa
activate Sistema
deactivate Sistema
Jugador -> Sala: Seleccionar sala y modo de juego
activate Sala
Sala -> Jugador: Confirmacion de selección 
deactivate Sala
Jugador -> Sistema: Iniciar juego
activate Sistema
Sistema -> Mecanica: Iniciar 
activate Mecanica
Mecanica -> Mecanica: Genera terminos segun nivel de dificultad y modo de juego
Mecanica --> Sistema: Muestra terminos y secuencia
deactivate Sistema
Jugador -> Jugador: Observa terminos durante 8 segundos 
Mecanica -> Sistema: Comienza Rondas
deactivate Mecanica
activate Sistema
Jugador -> Sistema: Ingresa secuencia
Sistema -> Mecanica: Respuestas
activate Mecanica
Mecanica -> Mecanica: Calcula puntuacion
Mecanica -> Sistema: Puntiacion en cada ronda
Jugador -> Sistema: Ultima Ronda
Sistema -> Mecanica: Envia respuestas
Mecanica -> Mecanica: Calcula las puntuaciones de los jugadores
Mecanica -> Sistema: Podio de ganadores 
deactivate Mecanica
Sistema -> Temporada: Obtener temporada actual
activate Temporada
Sistema -> Temporada: Envia Puntuacion para acumular
deactivate Sistema
Temporada-> Recompensas: Envia ganadores de la temporada
deactivate Temporada
activate Recompensas
Recompensas -> Recompensas: Calcula recompensas
Recompensas --> Temporada: Lista de ganadores y sus recompensas
deactivate Recompensas
activate Temporada
Temporada -> Sistema: Muestra Ganadores
deactivate Temporada
activate Sistema
Sistema -> Jugador: Envia Recompensas
deactivate Sistema

