--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-02-11 09:09:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16581)
-- Name: Laptops; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Laptops" (
    "Id" integer NOT NULL,
    "Nombre" text NOT NULL
);


ALTER TABLE public."Laptops" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16580)
-- Name: Laptops_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Laptops" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Laptops_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16575)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4897 (class 0 OID 16581)
-- Dependencies: 219
-- Data for Name: Laptops; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Laptops" ("Id", "Nombre") FROM stdin;
1	Lenovo
20	Otra
\.


--
-- TOC entry 4895 (class 0 OID 16575)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250201174446_TablaLaptops	9.0.1
\.


--
-- TOC entry 4903 (class 0 OID 0)
-- Dependencies: 218
-- Name: Laptops_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Laptops_Id_seq"', 21, true);


--
-- TOC entry 4749 (class 2606 OID 16587)
-- Name: Laptops PK_Laptops; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Laptops"
    ADD CONSTRAINT "PK_Laptops" PRIMARY KEY ("Id");


--
-- TOC entry 4747 (class 2606 OID 16579)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2025-02-11 09:09:43

--
-- PostgreSQL database dump complete
--

